export const GLOSSARY: Record<string, { plain: string; lens: string }> = {
    DOM: { plain: 'The browser’s tree of real HTML elements.', lens: 'Your layout and text layers.' },
    WebGL: { plain: 'A browser API that lets the GPU draw graphics in a canvas.', lens: 'A separate image stage below the HTML.' },
    state: { plain: 'The current values that describe what the interface is doing.', lens: 'A variant plus its changing properties.' },
    easing: { plain: 'A curve that changes speed during a timed animation.', lens: 'The graph editor between keyframes.' },
    damping: { plain: 'Gradually catching up to a changing target.', lens: 'A camera gently following a subject.' },
    ticker: { plain: 'A shared callback that runs on animation frames.', lens: 'The composition’s clock.' },
    stagger: { plain: 'A start-time offset between items in a group.', lens: 'Layers starting a few frames apart.' },
    'pointer capture': { plain: 'Keeping drag events attached to an element after the pointer leaves it.', lens: 'Continuing to hold an object outside its original frame.' },
    clamp: { plain: 'Keeping a value between a minimum and maximum.', lens: 'Hard stops at both ends of a slider.' },
    wrap: { plain: 'Returning a value to the opposite end of a repeating range.', lens: 'A seamless repeating pattern.' },
    modulo: { plain: 'The remainder after dividing by a cycle length; wrapping also corrects negative values.', lens: 'Where you are inside one repeat.' },
    texture: { plain: 'An image attached to a surface in a 3D scene.', lens: 'A photo fill on a rectangle.' },
    'vertex shader': { plain: 'A small GPU program that positions each point of a mesh.', lens: 'A formula-driven mesh warp.' },
    uniform: { plain: 'A shared input value sent to a shader.', lens: 'A dial applied to every point.' },
    perspective: { plain: 'A camera projection where closer things appear larger.', lens: 'The depth behavior of a real camera.' },
    'stroke dash': { plain: 'A repeating visible-and-hidden pattern along an SVG line.', lens: 'Trim Paths made from one long dash and one gap.' },
    timeline: { plain: 'An ordered set of animations with explicit start times.', lens: 'A mini After Effects composition.' },
    mask: { plain: 'A boundary that hides anything outside it.', lens: 'A clipping mask around a line of text.' },
    SplitText: { plain: 'A GSAP tool that separates rendered text into animatable lines, words, or characters.', lens: 'Separate text layers, generated from the real layout.' },
    interpolation: { plain: 'Finding a value between a start and an end at a given progress.', lens: 'An in-between keyframe.' },
    'shared element': { plain: 'One visual that connects two different layouts.', lens: 'A photo that becomes the detail photo instead of disappearing.' },
    inert: { plain: 'An HTML setting that temporarily disables interaction and focus in a region.', lens: 'Locking the background while a dialog is open.' },
    parallax: { plain: 'A depth impression made by layers moving at different speeds.', lens: 'A multiplane camera effect.' },
    normalize: { plain: 'Mapping a range of numbers into a standard 0-to-1 range.', lens: 'Turning any journey into a percentage.' },
    'state machine': { plain: 'Named stages with rules for moving between them.', lens: 'A flow between prototype states: idle, covering, swapping, revealing.' },
    'draw call': { plain: 'One command asking the GPU to draw a batch of geometry.', lens: 'One batch sent to the graphics stage.' },
    DPR: { plain: 'Device pixel ratio: the number of image pixels used per CSS pixel.', lens: 'Render resolution; more pixels cost more work.' },
    dispose: { plain: 'Explicitly releasing GPU resources that are no longer needed.', lens: 'Removing unused layers and freeing their memory.' },
    instancing: { plain: 'Drawing many copies of a shared shape/material in one batch.', lens: 'Many instances of one visual component.' },
};
